env: "local" # "local"/"dev"/"prod"
startup-status: 0 # 1/0. 1 - run. 0 - tests
address: 0.0.0.0 # the address where the microservice will be launched
service-port: 8082 # the port on which the microservice will be launched

postgres:
  host: "localhost"
  port: 5432
  user: "wnd"
  password: "123"
  dbname: "wnd"
  sslmode: "disable"

redis:
  address: "localhost:6379"
  password: ""
  db: 0
