env: "local" # "local"/"dev"/"prod"
startup-status: 1 # 1/0. 1 - run. 0 - tests
address: 0.0.0.0 # the address where the microservice will be launched
service-port: 8083 # the port on which the microservice will be launched
admin_name: admin
admin_password: pass123
admin_email: admin@mail
jwt_key: XU5AusKEA2MCVt5khTUsVvwHj90kBkLNyqqUCAZRixU= 

postgres:
  host: "localhost"
  port: 5432
  user: "wnd"
  password: "123"
  dbname: "wnd"
  sslmode: "disable"

redis:
  address: "localhost:6379"
  password: ""
  db: 0
